// The emoji the page offers: to put in a comment, to write as `:code:`, and to
// react with. `[emoji, code, words to find it by]` (the code as in GitHub's
// `:+1:`; the words are Japanese, and the code is searched too). The first
// eight are the ones offered at once for a reaction. Add to it here.
(function (D) {
  'use strict';
  D.emoji = [
    ['👍', '+1', 'いいね 賛成 ok 承認'],
    ['👎', '-1', 'だめ 反対 否定'],
    ['😄', 'smile', 'うれしい 笑顔 笑'],
    ['🎉', 'tada', 'おめでとう お祝い 祝'],
    ['😕', 'confused', '困惑 わからない 迷う'],
    ['❤️', 'heart', '好き ハート 愛'],
    ['🚀', 'rocket', '出荷 リリース 速い'],
    ['👀', 'eyes', '見た 確認 見てる 目'],
    ['✅', 'white_check_mark', '完了 ok チェック 済'],
    ['✔️', 'heavy_check_mark', 'チェック 済 正しい'],
    ['🙆', 'ok_woman', '了解 ok 大丈夫'],
    ['💯', '100', '満点 完璧 百点'],
    ['👌', 'ok_hand', 'ok 了解 いい'],
    ['🆗', 'ok', 'ok 了解'],
    ['🙌', 'raised_hands', 'やった 万歳 喜び'],
    ['👏', 'clap', '拍手 すごい'],
    ['💪', 'muscle', 'がんばれ 強い 力'],
    ['✨', 'sparkles', 'きれい 新しい 輝き'],
    ['🌟', 'star2', '星 すごい'],
    ['⭐', 'star', '星 お気に入り'],
    ['⚠️', 'warning', '注意 警告 危険'],
    ['❌', 'x', 'だめ バツ 誤り'],
    ['🚫', 'no_entry_sign', '禁止 やめて'],
    ['🛑', 'stop_sign', '停止 ストップ'],
    ['⛔', 'no_entry', '進入禁止 だめ'],
    ['🙅', 'no_good', 'ちがう だめ 違う'],
    ['🐛', 'bug', 'バグ 虫 不具合'],
    ['🐞', 'lady_beetle', 'バグ 虫 不具合'],
    ['🔒', 'lock', '鍵 セキュリティ 安全'],
    ['🔓', 'unlock', '鍵 開錠'],
    ['💥', 'boom', '衝突 壊れる 爆発'],
    ['🔥', 'fire', '炎 熱い 危険'],
    ['💣', 'bomb', '地雷 危険'],
    ['🚨', 'rotating_light', '警報 緊急 至急'],
    ['❗', 'exclamation', '重要 びっくり'],
    ['‼️', 'bangbang', '重要 強調'],
    ['❓', 'question', '質問 疑問 はてな'],
    ['❔', 'grey_question', '質問 疑問'],
    ['🤔', 'thinking', '考え中 悩む 迷う'],
    ['🧐', 'monocle_face', '詳しく 精査 よく見る'],
    ['😅', 'sweat_smile', '苦笑い 冷や汗 あせる'],
    ['😬', 'grimacing', '気まずい 微妙'],
    ['🙄', 'roll_eyes', 'やれやれ あきれる'],
    ['😢', 'cry', '悲しい 泣く'],
    ['😭', 'sob', '号泣 泣く'],
    ['😱', 'scream', '驚き 怖い 大変'],
    ['😮', 'open_mouth', '驚き えっ'],
    ['😳', 'flushed', '赤面 恥ずかしい'],
    ['🤷', 'shrug', 'わからない さあ'],
    ['🤦', 'facepalm', '頭を抱える やってしまった'],
    ['😵', 'dizzy_face', '混乱 めまい'],
    ['😞', 'disappointed', 'がっかり 残念'],
    ['😩', 'weary', '疲れた つらい'],
    ['🥺', 'pleading_face', 'お願い うるうる'],
    ['🙏', 'pray', 'ありがとう お願い 感謝'],
    ['😊', 'blush', 'ほほえみ 笑顔'],
    ['😀', 'grinning', '笑顔 にこにこ'],
    ['😁', 'grin', '笑顔 にっこり'],
    ['😂', 'joy', '爆笑 笑'],
    ['🤣', 'rofl', '大笑い 爆笑'],
    ['😉', 'wink', 'ウインク'],
    ['😎', 'sunglasses', 'かっこいい サングラス'],
    ['🥳', 'partying_face', 'パーティー お祝い'],
    ['🤩', 'star_struck', '感激 すごい'],
    ['😍', 'heart_eyes', '大好き'],
    ['🥰', 'smiling_face_with_hearts', '大好き うれしい'],
    ['😇', 'innocent', '天使 無実'],
    ['🤗', 'hugs', 'ハグ 歓迎'],
    ['🙂', 'slightly_smiling_face', 'にっこり 微笑'],
    ['😴', 'sleeping', '眠い 寝る'],
    ['🤝', 'handshake', '握手 合意 協力'],
    ['😌', 'relieved', 'ほっと 安心'],
    ['😤', 'triumph', 'むっ 得意'],
    ['😡', 'rage', '怒り 怒る'],
    ['🫡', 'saluting_face', '敬礼 了解'],
    ['🤞', 'crossed_fingers', '祈る うまくいく'],
    ['✌️', 'v', 'ピース 勝利'],
    ['👋', 'wave', 'こんにちは 手を振る さようなら'],
    ['👉', 'point_right', 'これ 右'],
    ['👈', 'point_left', 'これ 左'],
    ['👆', 'point_up_2', '上 これ'],
    ['👇', 'point_down', '下 これ'],
    ['💙', 'blue_heart', 'ハート 青'],
    ['💚', 'green_heart', 'ハート 緑'],
    ['💛', 'yellow_heart', 'ハート 黄'],
    ['💜', 'purple_heart', 'ハート 紫'],
    ['🧡', 'orange_heart', 'ハート オレンジ'],
    ['🖤', 'black_heart', 'ハート 黒'],
    ['💔', 'broken_heart', '失恋 悲しい'],
    ['⏳', 'hourglass_flowing_sand', '待ち 保留 砂時計'],
    ['⌛', 'hourglass', '待ち 時間'],
    ['🚧', 'construction', '作業中 工事'],
    ['🔧', 'wrench', '修正 道具 レンチ'],
    ['🔨', 'hammer', '金づち 修正'],
    ['🛠️', 'hammer_and_wrench', '修理 道具'],
    ['🧹', 'broom', '掃除 整理 片付け'],
    ['♻️', 'recycle', 'リファクタリング 再利用'],
    ['📝', 'memo', 'メモ ドキュメント 記録'],
    ['📌', 'pushpin', '固定 ピン'],
    ['📎', 'paperclip', '添付 クリップ'],
    ['🔗', 'link', 'リンク 参照'],
    ['📦', 'package', 'パッケージ 荷物'],
    ['🎯', 'dart', '目標 的 狙い'],
    ['💡', 'bulb', 'アイデア ひらめき 電球'],
    ['📖', 'book', '本 ドキュメント 読む'],
    ['🧪', 'test_tube', 'テスト 実験'],
    ['🧵', 'thread', 'スレッド 糸'],
    ['🔍', 'mag', '検索 調査 虫めがね'],
    ['🐢', 'turtle', '遅い かめ'],
    ['⚡', 'zap', '速い 高速 雷'],
    ['🐌', 'snail', '遅い かたつむり'],
    ['🤖', 'robot', 'ロボット 自動'],
    ['➕', 'heavy_plus_sign', '追加 プラス'],
    ['➖', 'heavy_minus_sign', '削除 マイナス'],
    ['🔁', 'repeat', '繰り返し ループ'],
    ['🆕', 'new', '新規 新しい'],
    ['💤', 'zzz', '眠い 放置'],
    ['🎁', 'gift', 'プレゼント'],
    ['🍺', 'beer', '乾杯 ビール'],
    ['☕', 'coffee', '休憩 コーヒー'],
    ['🍵', 'tea', 'お茶 休憩'],
    ['🌈', 'rainbow', '虹'],
    ['🌸', 'cherry_blossom', '桜 春'],
    ['🐱', 'cat', 'ねこ 猫'],
    ['🐶', 'dog', 'いぬ 犬'],
    ['🦄', 'unicorn', 'ユニコーン'],
    ['🙈', 'see_no_evil', '見ざる 見ない'],
    ['👻', 'ghost', 'おばけ 幽霊'],
    ['💩', 'poop', 'うんち'],
  ];
})(window.Diffnote = window.Diffnote || {});
